# Funciones Utiles

In [1]:
import pandas as pd

In [2]:
# Visualización de más de una salida
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Cargamos los tsv:

In [6]:
zonaprop_alquiler = pd.read_csv('../data/raw/zonaprop_alquiler_1776024151.tsv', sep = '\t')

zonaprop_alquiler.shape
zonaprop_alquiler.head()

(12000, 21)

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,58757240,zonaprop,alquiler,$ 750.000,$ 300.000,Mansilla,2936.0,NaN,Barrio Norte,...,Amplio departamento de dos ambientes en el exc...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
1,2026-04-12,58818211,zonaprop,alquiler,$ 1.700.000,$ 400.000,Cespedes,2300.0,NaN,Belgrano,...,"3 ambientes con balcón, y terraza con parrilla...",https://www.zonaprop.com.ar/propiedades/clasif...,1,0,0,0,1,0,0,0
2,2026-04-12,58564550,zonaprop,alquiler,USD 2.500,$ 1.150.000,Riobamba,1200.0,NaN,Recoleta,...,Departamento en alquiler de 4 ambientes con co...,https://www.zonaprop.com.ar/propiedades/clasif...,4,0,0,0,1,1,1,0
3,2026-04-12,58314210,zonaprop,alquiler,USD 1.300,NaN,Pereyra Lucena,2500.0,NaN,Palermo,...,Amoblado y Equipado. Ubicado a metros de Av. L...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,1,0,1,1
4,2026-04-12,58810878,zonaprop,alquiler,USD 3.800,NaN,Lola Mora,400.0,NaN,Puerto Madero,...,Alquiler temporario de 3 ambientes amueblado e...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,0,0,1,1,0,0

In [7]:
zonaprop_alquiler_temporal = pd.read_csv('../data/raw/zonaprop_alquiler_temporal_1776025830.tsv', sep = '\t')

zonaprop_alquiler_temporal.shape
zonaprop_alquiler_temporal.head()

(3476, 21)

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,58810877,zonaprop,alquiler_temporal,USD 3.800,NaN,Lola Mora,400.0,NaN,Puerto Madero,...,Alquiler temporario de 3 ambientes amueblado e...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,0,0,1,1,0,0
1,2026-04-12,58731045,zonaprop,alquiler_temporal,USD 1.100,NaN,Piedras,1100.0,NaN,San Telmo,...,Corredor Inmobiliario responsable: Arq. Jorge ...,https://www.zonaprop.com.ar/propiedades/clasif...,5,0,0,0,0,1,1,0
2,2026-04-12,58586992,zonaprop,alquiler_temporal,USD 600,NaN,Av. Las Heras,2000.0,NaN,Recoleta,...,Alquiler temporario de Departamento 1 Ambiente...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,0,0
3,2026-04-12,58822120,zonaprop,alquiler_temporal,USD 2.200,NaN,Rosario Vera Peñaloza,500.0,NaN,Puerto Madero,...,Corredor Inmobiliario responsable: Arq. Jorge ...,https://www.zonaprop.com.ar/propiedades/clasif...,4,0,0,0,1,1,1,0
4,2026-04-12,57872253,zonaprop,alquiler_temporal,USD 1.150,NaN,Arenales,2300.0,NaN,Recoleta,...,Departamento de dos ambientes para alquiler te...,https://www.zonaprop.com.ar/propiedades/clasif...,5,0,1,0,1,1,1,0

In [8]:
zonaprop_venta = pd.read_csv('../data/raw/zonaprop_venta_1776027996.tsv', sep = '\t')

zonaprop_venta.shape
zonaprop_venta.head()

(16274, 21)

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,58398326,zonaprop,venta,USD 160.000,$ 126.347,NaN,NaN,NaN,Villa Crespo,...,Hermoso tres ambientes reciclado en sexto piso...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
1,2026-04-12,57150909,zonaprop,venta,USD 4.500.000,$ 4.600.000,Posadas,1600.0,NaN,Recoleta,...,"Posadas esquina Bioy Casares, emblemático edif...",https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,1,1,0,0
2,2026-04-12,58790026,zonaprop,venta,USD 135.000,$ 230.000,Jerónimo Salguero,700.0,NaN,Almagro,...,"Departamento 2 ambientes con balcón al frente,...",https://www.zonaprop.com.ar/propiedades/clasif...,1,1,0,0,0,0,1,0
3,2026-04-12,58499682,zonaprop,venta,USD 93.000,$ 220.000,Uriarte,2400.0,NaN,Palermo Soho,...,Dos ambientes reciclado y amueblado (opcional)...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
4,2026-04-12,58164322,zonaprop,venta,USD 127.000,$ 230.000,Malabia,2200.0,NaN,Palermo,...,3 ambientes. Lateral. 58 M2. Vista parcial. To...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0

In [9]:
argenprop_alquiler = pd.read_csv('../data/raw/argenprop_alquiler.tsv', sep = '\t')

argenprop_alquiler.shape
argenprop_alquiler.head()

(9377, 21)

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,19120155,argenprop,alquiler,$ 890.000,NaN,Niceto Vega,5900.0,3,Palermo Soho,...,Alquiler - monoambiente luminoso en palermo ub...,https://www.argenprop.com/departamento-en-alqu...,5,0,1,0,0,0,1,0
1,2026-04-12,10779484,argenprop,alquiler,$ 1.600.000,$365.000,El Salvador,5500.0,3,Palermo Hollywood,...,Alquiler: $ 1.600.000 ó u$s 1.150. Expensas: $...,https://www.argenprop.com/departamento-en-alqu...,2,0,0,0,1,0,1,0
2,2026-04-12,17789860,argenprop,alquiler,USD 1.400,$269.000,Rodriguez Peña,2000.0,2,Recoleta,...,•Espectacular departamento de categoria de 3 a...,https://www.argenprop.com/departamento-en-alqu...,0,0,0,0,0,0,1,0
3,2026-04-12,19226675,argenprop,alquiler,$ 900.000,NaN,Honduras,4600.0,6,Palermo,...,1 ambiente con terraza única en palermo - amoe...,https://www.argenprop.com/departamento-en-alqu...,5,0,0,0,0,0,1,0
4,2026-04-12,19202770,argenprop,alquiler,$ 550.000,$187.000,Montevideo,1100.0,NaN,Recoleta,...,"Dueño alquila, montevideo al 1100, entre avda....",https://www.argenprop.com/departamento-en-alqu...,0,0,1,0,0,0,1,0

In [10]:
argenprop_alquiler_temporal = pd.read_csv('../data/raw/argenprop_alquiler_temporal.tsv', sep = '\t')

argenprop_alquiler_temporal.shape
argenprop_alquiler_temporal.head()

(4658, 21)

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,18402372,argenprop,alquiler_temporal,USD 950,NaN,Manuel Nicolas Savio,400.0,4,Las Cañitas,...,Excelente unidad. Amplio y luminoso departamen...,https://www.argenprop.com/departamento-en-alqu...,0,0,1,0,0,0,1,0
1,2026-04-12,11420984,argenprop,alquiler_temporal,$ 1.300.000,$325.000,Av Gral Luis Maria Campos,1100.0,2,Las Cañitas,...,Alquiler: $ 1.300.000 ó u$s 950. Expensas: $ 3...,https://www.argenprop.com/departamento-en-alqu...,0,0,1,0,0,1,0,0
2,2026-04-12,19368839,argenprop,alquiler_temporal,$ 650.000,$199.600,Concepción Arenal,3500.0,NaN,Palermo Hollywood,...,Alquiler monoambiente amoblado en palermo con ...,https://www.argenprop.com/departamento-en-alqu...,5,1,1,0,0,0,0,0
3,2026-04-12,18676695,argenprop,alquiler_temporal,USD 1.100,NaN,Coronel Diaz,1500.0,NaN,Palermo,...,Alquiler temporario departamento amueblado de ...,https://www.argenprop.com/departamento-en-alqu...,0,0,0,0,0,0,1,0
4,2026-04-12,13229688,argenprop,alquiler_temporal,USD 850,$300.000,Gral Lucio Mansilla,2600.0,NaN,Recoleta,...,Impecable 2 ambientes! Espectacular balcón ter...,https://www.argenprop.com/departamento-en-alqu...,5,0,1,0,0,1,1,1

In [11]:
argenprop_venta = pd.read_csv('../data/raw/argenprop_venta.tsv', sep = '\t')

argenprop_venta.shape
argenprop_venta.head()

(20395, 21)

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,18799423,argenprop,venta,USD 2.500.000,$2.400.000,Jerónimo Salguero,2700.0,NaN,Palermo Chico,...,“Torre bellini” de revista! Impecable piso muy...,https://www.argenprop.com/departamento-en-vent...,6,0,1,1,1,1,1,0
1,2026-04-12,15321644,argenprop,venta,USD 150.000,$260.000,Bulnes,1600.0,NaN,Botanico,...,Impecable! Balcón corrido al frente con vista ...,https://www.argenprop.com/departamento-en-vent...,0,0,1,1,1,1,1,0
2,2026-04-12,19247127,argenprop,venta,USD 113.000,$116.000,Ángel Justianiano Carranza,2300.0,NaN,Palermo Hollywood,...,Impecable monoambiente! Espectacular vista abi...,https://www.argenprop.com/departamento-en-vent...,0,0,1,1,0,1,1,0
3,2026-04-12,19344625,argenprop,venta,USD 330.000,$203.300,Araoz,1200.0,8,Palermo,...,Venta 4 ambientes con balcón palermo + cochera...,https://www.argenprop.com/departamento-en-vent...,1,0,0,0,1,1,1,0
4,2026-04-12,9070214,argenprop,venta,USD 270.000,$300.000,Honduras,3900.0,2,Palermo Viejo,...,"Venta semipiso 4 ambientes, dos baños completo...",https://www.argenprop.com/departamento-en-vent...,1,0,1,0,1,0,1,1

# Concatenamos todos los datos recolectados:

Como desarrollamos los scrapers para que todas las tablas tengan las mismas columnas, con el mismo formato, podemos concatenar directamente:

In [12]:
df_real_estate = pd.concat([zonaprop_alquiler,zonaprop_alquiler_temporal,zonaprop_venta,argenprop_alquiler,argenprop_alquiler_temporal,argenprop_venta])
df_real_estate.shape

(66180, 21)

In [13]:
df_real_estate.head()

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,58757240,zonaprop,alquiler,$ 750.000,$ 300.000,Mansilla,2936.0,NaN,Barrio Norte,...,Amplio departamento de dos ambientes en el exc...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
1,2026-04-12,58818211,zonaprop,alquiler,$ 1.700.000,$ 400.000,Cespedes,2300.0,NaN,Belgrano,...,"3 ambientes con balcón, y terraza con parrilla...",https://www.zonaprop.com.ar/propiedades/clasif...,1,0,0,0,1,0,0,0
2,2026-04-12,58564550,zonaprop,alquiler,USD 2.500,$ 1.150.000,Riobamba,1200.0,NaN,Recoleta,...,Departamento en alquiler de 4 ambientes con co...,https://www.zonaprop.com.ar/propiedades/clasif...,4,0,0,0,1,1,1,0
3,2026-04-12,58314210,zonaprop,alquiler,USD 1.300,NaN,Pereyra Lucena,2500.0,NaN,Palermo,...,Amoblado y Equipado. Ubicado a metros de Av. L...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,1,0,1,1
4,2026-04-12,58810878,zonaprop,alquiler,USD 3.800,NaN,Lola Mora,400.0,NaN,Puerto Madero,...,Alquiler temporario de 3 ambientes amueblado e...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,0,0,1,1,0,0

# Descargar el dataframe maestro:

In [15]:
import os

OUTPUT_DIR = "../data/raw"
os.makedirs(OUTPUT_DIR, exist_ok=True)

filename = "dataframe_maestro.tsv"
filepath = os.path.join(OUTPUT_DIR, filename)
df_real_estate.to_csv(filepath, sep='\t', index=False, encoding='utf-8-sig')
print(f"\n✅ ¡Éxito! Guardado en: {filepath}")

✅ ¡Éxito! Guardado en: ../data/raw/dataframe_maestro.tsv