## 1. Instalación de dependencias

### Opcion 1: Si tenes una sola instalacion de Python

In [ ]:
# pip install curl_cffi beautifulsoup4 pandas

### Opcion 2: Si tenes varias instalaciones de Python

In [1]:
# # Ejecutar esta celda una sola vez para instalar los paquetes
# # Despues de instalarse, se reinicia el kernel para que esten disponibles en las siguientes celdas

# import sys, subprocess, importlib

# PACKAGES = ["curl_cffi", "beautifulsoup4", "pandas"]

# def install_and_restart(packages):
#     installed_any = False
#     for pkg in packages:
#         mod = pkg.split("[")[0].replace("-", "_")  
#         try:
#             importlib.import_module(mod)
#         except ImportError:
#             print(f"Installing {pkg}...")
#             subprocess.check_call([sys.executable, "-m", "pip", "install", pkg])
#             installed_any = True
    
#     if installed_any:
#         print("\n✅ Packages installed. Restarting kernel...")
#         import IPython
#         IPython.Application.instance().kernel.do_shutdown(restart=True)
#     else:
#         print("✅ All packages already installed, no restart needed.")

# install_and_restart(PACKAGES)

## 2. Imports y funciones auxiliares

In [ ]:
import re
import os
import time
import pandas as pd
from datetime import date
from bs4 import BeautifulSoup
from curl_cffi import requests as cf_requests

# ──────────────────────────────────────────────
# UTILIDADES
# ──────────────────────────────────────────────

def clean_text(text):
    if not text: return None
    text = text.replace('\xa0', ' ')
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def parse_price(price_text):
    price_text = clean_text(price_text)
    precio = "Consultar"
    expensas = None
    p_match = re.search(r'(USD|ARS|\$)\s?[\$]?\s?([\d\.]+)', price_text)
    if p_match:
        precio = p_match.group(0).strip()
    e_match = re.search(r'[Ee]xp[^$\d]*([\d\.]+)', price_text)
    if not e_match:
        e_match = re.search(r'\+\s?\$?\s?([\d\.]+)', price_text)
    if e_match:
        expensas = e_match.group(0).strip()
    return precio, expensas

def extract_smart_features(row):
    texto = (str(row.get('Descripción', '')) + " " + str(row.get('Detalles', ''))).lower()
    return pd.Series({
        "Amenities":         sum(1 for x in ["amenities", "piscina", "pileta", "sum", "parrilla", "gym", "sauna", "laundry"] if x in texto),
        "Losa_Central":      1 if any(x in texto for x in ["losa radiante", "calefacción central", "caldera central", "piso radiante"]) else 0,
        "Aire_Acond":        1 if any(x in texto for x in ["aire acondicionado", "split", " a/c", "frío-calor"]) else 0,
        "Apto_Credito":      1 if "apto crédito" in texto or "apto credito" in texto else 0,
        "Cochera":           1 if any(x in texto for x in ["cochera", "espacio guarda coche", "estacionamiento", "guarda coche"]) else 0,
        "Seguridad":         1 if any(x in texto for x in ["vigilancia", "seguridad 24", "tótem", "totem", "encargado"]) else 0,
        "Luminoso":          1 if any(x in texto for x in ["luminoso", "todo luz", "vista abierta", "vista panorámica", "sol"]) else 0,
        "Balcon_Aterrazado": 1 if "aterrazado" in texto or "balcón terraza" in texto else 0,
    })


MESES = r'(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)'

def parse_address(address_raw):
    """
    Maneja todos los casos conocidos de ZonaProp:
    - 'Bolivia al 4400'                          → calle=Bolivia, altura=4400
    - 'Av Luis María Campos 1500'                → calle=Av Luis María Campos, altura=1500
    - 'Junín 1615 piso 13'                       → calle=Junín, altura=1615, piso=13
    - 'SAN JOSE 445. Entre Belgrano y Venezuela' → calle=SAN JOSE, altura=445
    - '11 de Septiembre de 1888 2231'            → calle=11 de Septiembre de 1888, altura=2231
    - 'Torres del Yacht - Juana Manso al 600'    → calle=Juana Manso, altura=600
    - 'Alvear Tower - Azucena Villaflor'         → calle=None, altura=None (sin número)
    - 'El Faro - 3 Ambientes + Dependencia'      → calle=None, altura=None (número no es altura)
    """
    calle = altura = piso = None
    if not address_raw:
        return calle, altura, piso

    try:
        # 1. Limpiar "al " antes de números
        cleaned = re.sub(r'\bal\s+', '', address_raw, flags=re.IGNORECASE)

        # 2. Si tiene guión, quedarse con el fragmento que tenga número de altura válido
        #    Ej: "Alvear Tower - Azucena Villaflor" → ningún fragmento tiene número → None
        #    Ej: "Torres del Yacht - Juana Manso 600 - 2 Ambientes" → "Juana Manso 600"
        #    Ej: "El Faro - 3 Ambientes" → el "3" no es altura válida (< 10), descartar
        if '-' in cleaned:
            fragmentos = [f.strip() for f in cleaned.split('-')]
            candidato = None
            for frag in fragmentos:
                # Buscar fragmento con número >= 100 (alturas reales de CABA son >= 100)
                if re.search(r'\b\d{3,5}\b', frag):
                    candidato = frag
                    break
            if candidato:
                cleaned = candidato
            else:
                # Ningún fragmento tiene altura válida → nombre de edificio sin dirección
                return None, None, None

        # 3. Intentar capturar piso: "Junín 1615 piso 13"
        match_piso = re.search(
            r'([A-Za-záéíóúÁÉÍÓÚñÑü\s\.]+?)\s+(\d{2,5})\s+piso\s+(\d+)',
            cleaned, re.IGNORECASE
        )
        if match_piso:
            num = int(match_piso.group(2))
            if not (1800 <= num <= 1950 and re.search(MESES, cleaned[:match_piso.start(2)], re.IGNORECASE)):
                calle  = match_piso.group(1).strip().strip('-').strip('.').title()
                altura = match_piso.group(2).strip()
                piso   = match_piso.group(3).strip()
                return calle, altura, piso

        # 4. Iterar todos los números y encontrar la altura real
        for m in re.finditer(r'(\d{2,5})(?:[.,\s\-]|$)', cleaned):
            num = int(m.group(1))

            # Descartar números < 100: probablemente ambientes, m², baños, etc.
            if num < 100:
                continue

            # Descartar años históricos si hay un mes en el contexto previo
            contexto_previo = cleaned[:m.start()].lower()
            es_año_historico = (1800 <= num <= 1950) and bool(re.search(MESES, contexto_previo, re.IGNORECASE))
            if es_año_historico:
                continue

            # Este número es la altura real
            calle_raw = cleaned[:m.start()].strip().strip('-').strip('.').strip()
            if not calle_raw:
                continue

            calle  = calle_raw.title()
            altura = str(num)
            # piso queda None
            return calle, altura, piso

    except:
        pass

    return None, None, None

def parse_card(item):
    # Link
    href = item.get('data-to-posting', '')
    if not href:
        a = item.find('a', href=re.compile(r'/propiedades/'))
        href = a['href'] if a else ''
    link = f"https://www.zonaprop.com.ar{href}" if href.startswith('/') else href

    # Precio
    price_tag = item.find(attrs={"data-qa": "POSTING_CARD_PRICE"})
    precio_raw = clean_text(price_tag.text) if price_tag else ""
    precio, _ = parse_price(precio_raw)

    # Expensas
    exp_tag = item.find(attrs={"data-qa": "expensas"})
    expensas = clean_text(exp_tag.text) if exp_tag else None
    expensas = expensas[:-9] if expensas else None

    # ── Dirección: calle+altura y barrio van en tags separados ──
    addr_tag = item.find(class_=re.compile(r'location-address'))
    raw_address = clean_text(addr_tag.text) if addr_tag else ""
    calle, altura, piso = parse_address(raw_address)

    # Barrio/zona (el data-qa="POSTING_CARD_LOCATION")
    barrio_tag = item.find(attrs={"data-qa": "POSTING_CARD_LOCATION"})
    barrio = clean_text(barrio_tag.text) if barrio_tag else None
    barrio = barrio.split(',')[0].strip() if barrio else None

    # Características
    feat_tag = item.find(attrs={"data-qa": "POSTING_CARD_FEATURES"})
    features = clean_text(feat_tag.get_text(separator=' ')) if feat_tag else None

    # Descripción
    desc_tag = item.find(attrs={"data-qa": "POSTING_CARD_DESCRIPTION"})
    desc = clean_text(desc_tag.text) if desc_tag else None

    return link, precio, expensas, calle, altura, piso, barrio, features, desc

print("✅ Funciones utilitarias cargadas.")

✅ Funciones utilitarias cargadas.

## 3. Función principal del scrapper

In [7]:
def run_scrapper_zonaprop(enlace, operacion, max_pages=3):
    BASE = enlace
    OUTPUT_DIR = "../../data/raw"
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    all_data = []
    seen_links = set()

    for page_num in range(1, max_pages + 1):
        url = f"{BASE}.html" if page_num == 1 else f"{BASE}-pagina-{page_num}.html"
        print(f"\n--- PÁGINA {page_num} ---")
        print(f"URL: {url}")

        try:
            r = cf_requests.get(
                url,
                impersonate="chrome120",
                timeout=20,
                headers={
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                    "Accept-Language": "es-AR,es;q=0.9",
                    "Referer": "https://www.zonaprop.com.ar/",
                }
            )
            if r.status_code != 200:
                print(f"❌ Status {r.status_code}. Deteniendo.")
                break
        except Exception as e:
            print(f"❌ Error de red: {e}")
            break

        soup = BeautifulSoup(r.text, 'html.parser')
        items = soup.find_all('div', attrs={"data-qa": "posting PROPERTY"})

        if not items:
            print("⚠️ No se encontraron cards. Fin del listado.")
            break

        print(f"  → {len(items)} propiedades encontradas")

        for item in items:
            try:
                link, precio, expensas, calle, altura, piso, barrio, features, desc = parse_card(item)

                if not link or link in seen_links:
                    continue
                seen_links.add(link)

                print(f"  → {calle} {altura} | {precio}")
                
                all_data.append({
                    "Fecha_Scraping": date.today().isoformat(),
                    "Posting_ID":     item.get('data-id'),
                    "Sito":           'zonaprop',
                    "Operación":      operacion,
                    "Precio":         precio,
                    "Expensas":       expensas,
                    "Calle":          calle,
                    "Altura":         altura,
                    "Piso":           piso,
                    "Barrio":         barrio,       
                    "Detalles":       features,
                    "Descripción":    desc,
                    "Link":           link,
                })

            except Exception as e:
                print(f"    ⚠️ Error en card: {e}")
                continue

        time.sleep(2)

    if not all_data:
        print("⚠️ No se obtuvieron datos.")
        return None

    df = pd.DataFrame(all_data)
    features_df = df.apply(extract_smart_features, axis=1)
    df = pd.concat([df, features_df], axis=1)

    filename = f"zonaprop_{operacion}_{int(time.time())}.tsv"
    filepath = os.path.join(OUTPUT_DIR, filename)
    df.to_csv(filepath, sep='\t', index=False, encoding='utf-8-sig')
    print(f"\n✅ ¡Éxito! Guardado en: {filepath}")
    return df

print("✅ Listo.")

✅ Listo.

## 4. ▶️ Ejecutar el scrapper

# Alquiler

In [ ]:
df_alquiler = run_scrapper_zonaprop('https://www.zonaprop.com.ar/departamentos-alquiler-capital-federal', 'alquiler', max_pages=400)

--- PÁGINA 1 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-capital-federal.html
  → 30 propiedades encontradas
  → Mayor Arturo Luisoni 2600 | USD 450
  → Azucena Villaflor 669 | USD 6.000
  → Luis María Campos 1500 | USD 1.200
  → Colpayo 700 | USD 1.150
  → La Pampa 1100 | USD 2.200
  → None None | USD 1.300
  → Av. Libertador 2700 | USD 3.700
  → República De La India 3000 | USD 1.800
  → Paraguay 5600 | $ 600.000
  → Parana 1000 | $ 560.000
  → Macacha Guemes 330 | USD 4.600
  → Republica De Eslovenia 1900 | USD 1.000
  → Balbin 3695 | $ 690.000
  → Estomba 3700 | USD 750
  → Forest 400 | $ 650.000
  → Julián Alvarez 2360 | $ 830.000
  → Luis M Campos 1000 | $ 1.300.000
  → La Pampa 1300 | $ 890.000
  → Bernardo Irigoyen 1300 | $ 650.000
  → Comodoro Rivadavia 2320 | USD 2.000
  → Av. Del Libertador 2200 | USD 7.500
  → Salguero 3000 | USD 1.100
  → Av. Del Libertador 5700 | USD 1.100
  → Urdininea 1700 | $ 960.000
  → Paraguay 4800 | USD 1.100
  → Jose Hernandez 1400 | USD 450
  → Azopardo 700 | $ 900.000
  → Juncal 1800 | USD 1.000
  → Soler 4400 | $ 2.100.000
  → Soler 3900 | $ 970.000

--- PÁGINA 2 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-capital-federal-pagina-2.html
  → 30 propiedades encontradas
  → Charcas 3900 | $ 1.100.000
  → Ciudad De La Paz 300 | USD 800
  → Jorge Luis Borges 2300 | $ 1.600.000
  → Rivera 4300 | $ 2.200.000
  → Neuquen 1800 | $ 1.200.000
  → Del Libertador 2700 | USD 3.700
  → Macacha Güemes 300 | USD 4.500
  → Echeverria 1500 | $ 1.000.000
  → Bulnes 2700 | USD 1.400
  → Huergo 500 | USD 900
  → Demaria 4400 | USD 12.000
  → Valentin Virasoro 700 | $ 550.000
  → None None | USD 2.100
  → Av. Luis Maria Campos 1400 | $ 1.300.000
  → Vilela 2500 | USD 1.700
  → Av. Rivadavia 3585 | $ 850.000
  → Republica De Eslovenia 1900 | USD 2.450
  → Bartolome Mitre 1700 | $ 700.000
  → Montevideo 1100 | $ 600.000
  → Cerrito 1500 | $ 1.900.000
  → Talcahuano 1200 | USD 8.000
  → Echeverría 2700 | $ 1.300.000
  → La Pampa 600 | USD 6.000
  → Vidal 2300 | $ 1.000.000
  → Ayacucho 2100 | USD 1.400
  → Av. San Martin 3420 | $ 500.000
  → La Pampa 4315 | USD 1.700
  → Guatemala 5100 | USD 6.500
  → Av. Callao 1900 | USD 1.200
  → Manzanares 1600 | USD 550

--- PÁGINA 3 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-capital-federal-pagina-3.html
  → 30 propiedades encontradas
  → Av Del Libertador 800 | $ 1.400.000
  → Ángel Justiniano Carranza 1200 | $ 600.000
  → Melincue 3200 | $ 650.000
  → Marta Lynch 400 | USD 4.300
  → Las Heras 1800 | USD 1.500
  → Juncal 1800 | USD 1.000
  → Rojas 300 | $ 850.000
  → Ecuador 1200 | $ 2.050.000
  → None None | USD 800
  → Mora Fernández 2900 | USD 2.900
  → Berthelot 3300 | USD 1.900
  → Pacheco De Melo 2900 | USD 600
  → Sarmiento 4300 | $ 990.000
  → Camila O Gorman 373 | USD 2.500
  → Junin 600 | $ 550.000
  → Gorostiaga 1700 | USD 1.500
  → Avenida Del Libertador 6100 | USD 1.300
  → Huergo 400 | USD 1.200
  → Paraguay 4500 | $ 800.000
  → Huergo 500 | USD 1.000
  → Av. Cabildo 3600 | $ 920.000
  → La Pampa 1300 | $ 890.000
  → Austria 2566 | USD 1.300
  → Teodoro García 2400 | $ 1.400.000
  → Guatemala 5100 | USD 2.000
  → Manuel Ugarte 1500 | USD 750
  → Migueletes 2100 | USD 900
  → O'Higgins 2800 | $ 850.000
  → Alvear 1500 | USD 5.000
  → Juana Azurduy 2600 | $ 1.200.000

✅ ¡Éxito! Guardado en: ../../data/raw/zonaprop_alquiler_1776215534.tsv

In [6]:
if df_alquiler is not None:
    print(f"Total propiedades: {len(df_alquiler)}")
    display(df_alquiler.head(10))

    cols = ["Losa_Central","Aire_Acond","Apto_Credito",
            "Cochera","Seguridad","Luminoso","Balcon_Aterrazado"]
    print("\n📊 % con cada característica:")
    print((df_alquiler[cols].mean() * 100).round(1).astype(str) + "%")

Total propiedades: 90

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-14,58601056,zonaprop,alquiler,$ 630.000,$ 150.000,Malabia,2097,None,Palermo,...,Hermoso Monoambiente en inmejorable ubicación ...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,1,0,0,0,1,0
1,2026-04-14,58708042,zonaprop,alquiler,$ 550.000,$ 140.000,Av. Belgrano,200,None,Monserrat,...,[mel-Ver datos] Departamento de dos ambientes ...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,0,0
2,2026-04-14,58420784,zonaprop,alquiler,USD 1.200,$ 375.000,Huergo,400,None,Puerto Madero,...,Broker: Lali +54 9 11 Ver datosDos ambientes e...,https://www.zonaprop.com.ar/propiedades/clasif...,4,0,1,0,1,1,1,0
3,2026-04-14,58846126,zonaprop,alquiler,$ 660.000,$ 60.000,Diaz Colodrero,3500,None,Villa Urquiza,...,Fratelli grupo inmobiliario 11 Ver datosalquil...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,0,0,0,0,1,0
4,2026-04-14,58788957,zonaprop,alquiler,USD 3.700,$ 1.068.000,Av. Del Libertador,3100,None,Palermo Chico,...,Semipiso de Categoría en Palermo Chico con Coc...,https://www.zonaprop.com.ar/propiedades/clasif...,0,1,1,0,1,1,0,0
5,2026-04-14,58798784,zonaprop,alquiler,$ 800.000,$ 80.000,Dr. Pedro Ignacio Rivera,2600,None,Belgrano,...,Monoambiente al contrafrente con balcón francé...,https://www.zonaprop.com.ar/propiedades/clasif...,3,1,0,0,0,0,0,0
6,2026-04-14,58481534,zonaprop,alquiler,$ 1.300.000,None,Conde,1839,None,Belgrano R,...,Edificio torre rodeado de jardines. 4 ambiente...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
7,2026-04-14,58787314,zonaprop,alquiler,$ 900.000,$ 184.000,Valle,1100,None,Caballito,...,Semipiso de 1 dormitorio en alquiler en Caball...,https://www.zonaprop.com.ar/propiedades/clasif...,1,0,1,0,0,0,1,0
8,2026-04-14,58791528,zonaprop,alquiler,USD 750,$ 200.000,None,None,None,Palermo,...,_ Departamento de un dormitorio en alquiler ub...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
9,2026-04-14,58770031,zonaprop,alquiler,USD 1.300,$ 407.000,None,None,None,Recoleta,...,"Luminoso departamento contrafrente, a amplio p...",https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,1,1,0

📊 % con cada característica:
Losa_Central         16.7%
Aire_Acond           42.2%
Apto_Credito          2.2%
Cochera              36.7%
Seguridad            27.8%
Luminoso             71.1%
Balcon_Aterrazado     5.6%
dtype: object

# Alquiler Temporal

In [10]:
df_alquiler_temporal = run_scrapper_zonaprop('https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal', 'alquiler_temporal', max_pages=116)

--- PÁGINA 1 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal.html
  → 27 propiedades encontradas
  → Lola Mora 400 | USD 3.800
  → Piedras 1100 | USD 1.100
  → Av. Las Heras 2000 | USD 600
  → Rosario Vera Peñaloza 500 | USD 2.200
  → Arenales 2300 | USD 1.150
  → Av Rivadavia 5800 | USD 650
  → Av Coronel Diaz 1400 | USD 1.450
  → Nuñez 2900 | USD 650
  → Concepcion Arenal 2900 | USD 4.000
  → Marcelo T. De Alvear 500 | USD 700
  → Vera 800 | USD 700
  → Avenida Coronel Díaz 2400 | USD 1.250
  → Corrientes 1100 | USD 1.000
  → Riobamba 900 | USD 2.200
  → Emilio Ravignani 2300 | USD 1.100
  → Godoy Cruz 2900 | USD 1.400
  → Avenida Corrientes 1400 | USD 800
  → San Jose 445 | USD 550
  → Avalos 1900 | USD 750
  → Julián Álvarez 1900 | USD 700
  → Guemes 3600 | USD 800
  → Jose A Cabrera 3100 | USD 750
  → Ibera 2300 | USD 700
  → Lafinur 3200 | USD 1.900
  → Av Luis Maria Campos 300 | USD 750
  → Jorge Newberry 2500 | USD 1.200
  → Thompson 733 | USD 1.250

--- PÁGINA 2 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-2.html
  → 30 propiedades encontradas
  → Tucumán 3500 | USD 700
  → Libertador 2500 | USD 8.000
  → Cerviño 3700 | $ 1.500.000
  → Guemes 3600 | USD 1.500
  → Posadas 1500 | USD 1.550
  → Ortega Y Gasset 1800 | USD 1.600
  → Sanchez De Bustamante 2000 | USD 1.200
  → Godoy Cruz 2400 | $ 2.250.000
  → None None | USD 850
  → Av. Corrientes 1600 | USD 850
  → Arevalo 1400 | USD 800
  → Godoy Cruz 1500 | USD 1.100
  → Villarroel 1300 | USD 1.200
  → Guatemala 5000 | USD 900
  → Huergo 500 | USD 900
  → San Martín 900 | USD 550
  → Pagano 2600 | USD 1.350
  → Junín 1615 | USD 1.200
  → Pacheco De Melo 2700 | $ 650.000
  → Guemes 3000 | USD 1.500
  → Costa Rica 5500 | $ 800.000
  → Chenaut 1800 | USD 1.300
  → Dorrego 2700 | USD 1.050
  → Pacheco De Melo, Jose 2734 | USD 600
  → Viamonte 1359 | $ 600.000
  → Colpayo 380 | USD 900
  → Fitz Roy 2337 | USD 1.300
  → Santa Fe 5381 | USD 1.100
  → Rodriguez Peña 1800 | USD 2.000
  → Av. Pueyrredon 2300 | USD 2.200

--- PÁGINA 3 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-3.html
  → 30 propiedades encontradas
  → Costa Rica 4100 | USD 900
  → Pueyrredon 1700 | USD 750
  → Av Regimiento Patricios 200 | USD 700
  → Las Heras 3700 | USD 950
  → Arevalo 1400 | USD 800
  → Amenabar 3100 | USD 1.200
  → None None | USD 700
  → Monroe 2200 | USD 1.150
  → Teodoro Garcia 2800 | USD 1.100
  → Roosevelt 2800 | USD 1.500
  → Sanchez De Bustamante 2100 | USD 1.500
  → Humboldt 1900 | USD 2.000
  → Azopardo 770 | USD 850
  → Costa Rica 3900 | USD 1.500
  → 3 De Febrero 700 | USD 1.100
  → Avenida Coronel Díaz 2400 | USD 1.250
  → Godoy Cruz 2400 | USD 1.400
  → Directorio 3900 | USD 1.000
  → Salguero 3000 | $ 920.000
  → 3 De Febrero 2552 | USD 800
  → Doblas 200 | USD 1.000
  → Libertad 800 | USD 950
  → Rodríguez Peña 1500 | USD 950
  → Costa Rica 3900 | USD 1.000
  → Ruggieri 2900 | USD 2.200
  → Av Scalabrini Ortiz 1600 | USD 750
  → Gelly 3400 | $ 800.000
  → Sánchez De Bustamante 2100 | USD 1.500
  → Rivadavia 1300 | USD 650
  → Av. Juana Manso 1500 | USD 2.200

--- PÁGINA 4 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-4.html
  → 30 propiedades encontradas
  → Adolfo Alsina 1928 | USD 400
  → Juana Manso 400 | USD 2.800
  → Fray Luis Beltran 100 | $ 1.000.000
  → Costa Rica 3900 | USD 1.500
  → Reconquista 642 | USD 550
  → Arenales 3800 | USD 1.500
  → Av San Juan 2800 | USD 800
  → Maipu 359 | USD 800
  → Romulo Naon 3500 | USD 600
  → Mansilla 2600 | USD 850
  → Departamento En Alquiler En Palermo 1 Dormitorio, Billinghurst 1300 | $ 1.100.000
  → Avenida Olleros 1700 | $ 500.000
  → Santa Fe 2200 | USD 1.800
  → Junin 1600 | USD 3.500
  → Av Scalabrini Ortiz 1507 | USD 900
  → Monroe 2671 | USD 750
  → Paraguay 1200 | USD 1.000
  → Guemes 3300 | USD 5.000
  → Borges Jorge Luis 2287 | USD 550
  → Ayacucho 2100 | USD 1.500
  → Cerviño 3500 | USD 4.000
  → Senillosa 100 | USD 1.250
  → Miller 3100 | USD 600
  → Soler 6055 | USD 700
  → Anchorena 1100 | USD 1.400
  → Zelarrayan 1600 | USD 600
  → Av Del Libertador 7800 | USD 1.200
  → Av Libertador 4800 | USD 850
  → Soldado De La Independencia 900 | USD 600
  → Paraguay 500 | USD 600

--- PÁGINA 5 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-5.html
  → 30 propiedades encontradas
  → Suipacha 1300 | USD 800
  → Amenabar 100 | USD 1.400
  → Ecuador 1578 | USD 1.100
  → Juana Manso 156 | USD 3.000
  → Av Santa Fe 5000 | USD 800
  → Elpidio Gonzalez 4900 | USD 650
  → Olazabal, Av 5550 | $ 750.000
  → Avenida San Juan 2400 | $ 650.000
  → Guatemala 5000 | USD 1.100
  → Perón 4100 | USD 600
  → Libertador 200 | USD 650
  → Venezuela 964 | $ 800.000
  → Juncal 2508 | USD 600
  → Ayacucho 1800 | USD 900
  → Juana Manso 740 | USD 2.800
  → Comodoro Pedro Zanni 300 | USD 1.000
  → Av. Libertador 7700 | USD 6.900
  → Avenida Alvear 1939 | USD 1.700
  → Senillosa 100 | USD 1.200
  → Av. Independencia 2300 | USD 900
  → Juana Manso 1600 | USD 1.600
  → Araoz 2288 | USD 700
  → Humboldt 2300 | USD 800
  → Jorge Luis Borges 2000 | USD 1.500
  → None None | USD 800
  → Clay 2800 | USD 1.700
  → Billinghurts 1611 | USD 800
  → Av. Independencia 2251 | USD 650
  → Bernardo De Irigoyen 800 | USD 750
  → None None | USD 1.300

--- PÁGINA 6 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-6.html
  → 30 propiedades encontradas
  → Aguilar 2400 | USD 1.400
  → Camargo 1050 | USD 1.000
  → Olleros 4100 | USD 780
  → Godoy Cruz 2900 | USD 1.500
  → Av. Gral. Las Heras 3700 | USD 800
  → Avenida Alvear 1400 | USD 5.200
  → Charcas 3200 | $ 1.100.000
  → Ugarteche 2800 | USD 800
  → Guatemala 4800 | USD 1.300
  → Santa Fe 2600 | USD 550
  → Sanchez De Bustamante 2300 | USD 2.000
  → Brasil 724 | $ 850.000
  → Marcelo T. De Alvear 600 | $ 550.000
  → Rivadavia 1900 | USD 1.000
  → Juncal 4690 | USD 1.500
  → Juana Manso 1100 | USD 1.200
  → Juana Manso 670 | USD 1.850
  → Guatemala 5700 | USD 1.500
  → Ramírez De Velazco 300 | USD 950
  → Nicaragua 5600 | USD 1.100
  → Bulnes 2700 | USD 2.500
  → Av Diaz Vélez 4100 | $ 685.000
  → Zabala 3500 | $ 880.000
  → Costa Rica 4200 | USD 500
  → Tacuari 1100 | USD 700
  → Humboldt 1900 | USD 2.100
  → Rivadavia 1600 | USD 1.200
  → Fitz Roy 2400 | $ 900.000
  → Cerviño 4700 | USD 6.000
  → Santa Fe 5100 | USD 1.100

--- PÁGINA 7 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-7.html
  → 30 propiedades encontradas
  → Callao 400 | $ 900.000
  → Araoz 1900 | $ 600.000
  → Gutierrez 2700 | USD 650
  → Miguletes 500 | USD 1.200
  → Paraguay 5645 | $ 1.250.000
  → Aime Paine 1500 | USD 1.400
  → Av. Gral. Indalecio Chenaut 1800 | USD 1.300
  → Marcelo T Alvear 2400 | USD 1.200
  → None None | USD 1.600
  → Avenida Monroe 3600 | $ 850.000
  → Soldado De La Independencia 700 | USD 1.500
  → Chile 300 | USD 600
  → José A. Cabrera 3153 | USD 850
  → None None | USD 450
  → Monroe 5674 | USD 480
  → None None | USD 1.200
  → Fernández 305 | $ 900.000
  → Soldado De La Independencia 900 | USD 3.900
  → Avenida Córdoba 6570 | $ 980.000
  → Lavalle 3086 | USD 650
  → Ramsay 2055 | USD 12.000
  → Virrey Arredondo 2553 | USD 900
  → Vidal 2962 | USD 750
  → Guemes 4600 | USD 1.300
  → Rodríguez Peña 1180 | USD 900
  → Paraguay 3007 | USD 1.400
  → Aime Paine 1500 | USD 1.400
  → Olga Cossettini 1631 | USD 1.200
  → Coronel Niceto Vega 5074 | USD 700
  → Arévalo 2700 | USD 1.700

--- PÁGINA 8 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-8.html
  → 30 propiedades encontradas
  → Moreno 500 | USD 1.200
  → Avenida Cerviño 3800 | USD 600
  → Charcas 4900 | USD 650
  → Juncal 2300 | USD 1.200
  → Montañeses 2342 | $ 650.000
  → Thames 1800 | Consultar
  → Juana Manso 1746 | USD 2.500
  → Libre Desde 6/4 19/4 Peña 2100 | USD 60
  → José Andrés Pacheco De Melo 2666 | USD 850
  → Charcas 4300 | USD 1.650
  → Paraguay 2600 | USD 850
  → Arenales 1100 | USD 600
  → Beruti 4437 | USD 1.050
  → Mansilla 3700 | USD 1.400
  → Bulnes 1100 | USD 900
  → None None | USD 1.100
  → Juana Manso 1600 | USD 700
  → Av Jorge Newbery 2400 | USD 1.200
  → Aguero 2100 | USD 550
  → Julián Álvarez 2372 | USD 1.100
  → Concepción Arenal 2421 | USD 800
  → Yatay 500 | USD 550
  → Austria 2100 | USD 1.250
  → Lola Mora 400 | USD 1.800
  → Avenida Alicia Moreau De Justo 1000 | USD 700
  → None None | USD 900
  → Virrey Arredondo 2400 | USD 750
  → Fray Justo Santa María De Oro 2567 | USD 800
  → Larrea 1200 | $ 1.200.000
  → Virrey Avilés 2800 | USD 1.000

--- PÁGINA 9 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-9.html
  → 30 propiedades encontradas
  → Federico Lacroze 1752 | USD 900
  → Guemes 3300 | USD 750
  → Raúl Scalabrini Ortiz 1771 | USD 700
  → Arenales 1600 | USD 1.500
  → Armenia 2104 | USD 800
  → Av Santa Fe 2300 | USD 750
  → None None | USD 2.000
  → Godoy Cruz 1500 | USD 900
  → Lavalleja 600 | USD 500
  → Armenia 1300 | $ 1.900.000
  → Martha Salotti 540 | USD 3.000
  → Viamonte 600 | $ 1.100.000
  → Gorriti 4033 | $ 1.200
  → Guatemala 6061 | USD 1.000
  → Av. Garay 400 | USD 1.200
  → Julián Álvarez 510 | USD 1.100
  → Arenales 1900 | USD 50
  → Av Belgrano 300 | USD 700
  → Martha Lynch 500 | USD 3.500
  → Migueletes 700 | USD 800
  → Baez 793 | USD 850
  → Fernandez 324 | $ 550.000
  → República De Eslovenia 1907 | USD 650
  → None None | USD 1.400
  → Sarmiento 2300 | USD 700
  → Independencia Av 600 | $ 480.000
  → Av. Gral. Indalecio Chenaut 1730 | USD 2.200
  → Juncal 4600 | USD 3.500
  → None None | $ 550.000
  → Lafinur 2900 | USD 1.800

--- PÁGINA 10 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-10.html
  → 30 propiedades encontradas
  → Av. Cabildo 130 | USD 1.000
  → Guemes 3355 | USD 1.300
  → Salguero 2700 | USD 6.000
  → Gorriti 6060 | USD 1.100
  → Paraguay 1100 | USD 1.050
  → Lola Mora 400 | USD 2.100
  → None None | USD 550
  → Sanchez De Bustamante 2500 | USD 950
  → Juncal 1648 | USD 700
  → Lavalle 1700 | USD 550
  → Beruti 2800 | USD 1.500
  → Uruguay 300 | USD 600
  → Arce 500 | USD 900
  → Concepción Arenal 2989 | USD 1.300
  → Juana Manso 1636 | USD 1.400
  → None None | USD 650
  → None None | USD 950
  → Rivadavia 4700 | USD 700
  → Ambientes En Avenida Nazca 4500 | $ 1.200.000
  → Pueyrredón 2200 | USD 850
  → French 2200 | USD 2.300
  → C. Silvio L. Ruggeri 2900 | USD 2.000
  → Av Del Libertador 8122 | USD 1.400
  → Fernández 324 | $ 750.000
  → Alvear 1800 | USD 2.000
  → None None | USD 1.100
  → Guatemala 4700 | USD 1.400
  → None None | Consultar
  → Jaramillo 2364 | USD 1.000
  → Coronel Diaz 1800 | USD 1.700

--- PÁGINA 11 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-11.html
  → 30 propiedades encontradas
  → Camila O'Gorman 373 | USD 1.000
  → Comodoro Pedro Zanni 300 | USD 950
  → Vidt 2000 | USD 4.700
  → Huergo 400 | USD 1.800
  → Andres Pacheco De Melo 1859 | USD 950
  → Juana Manso 500 | USD 2.400
  → Güemes 3300 | USD 1.500
  → Armenia 2116 | USD 550
  → Serrano 200 | USD 800
  → Rep. Arabe Siria 3100 | USD 580
  → Palpa 2419 | USD 950
  → Avenida Del Libertador 700 | $ 550.000
  → None None | USD 1.100
  → Guatemala 5600 | USD 1.200
  → Sucre, Antonio J. De 4273 | USD 1.100
  → Av. Francisco Bilbao 1300 | USD 990
  → Costa Rica 3900 | USD 620
  → San Luis 2400 | $ 750.000
  → Juana Manso 600 | USD 2.500
  → Arenales 2300 | USD 700
  → Juan Domingo Perón 4100 | USD 700
  → Marta Lynch 500 | USD 4.000
  → Avenida Santa Fe 4016 | USD 1.250
  → None None | USD 1.400
  → None None | USD 1.400
  → Av. Gral. Las Heras 2048 | USD 1.000
  → Hortiguera 200 | USD 750
  → Paraguay 3800 | USD 1.100
  → None None | USD 2.500
  → Avenida Garay 655 | $ 790.000

--- PÁGINA 12 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-12.html
  → 30 propiedades encontradas
  → Av. Cabildo 172 | USD 700
  → None None | USD 750
  → Cabrera 3100 | USD 700
  → Sucre 4100 | USD 600
  → Olazábal 3200 | USD 1.400
  → Ambientes. Juncal 3000 | $ 650.000
  → Esmeralda 1066 | USD 550
  → None None | USD 600
  → Carlos Gardel 3100 | USD 600
  → Tucumán 3500 | USD 720
  → Camila O`Gorman 417 | USD 1.000
  → Luis María Campos 600 | USD 670
  → Bauness 1960 | USD 650
  → Avenida Callao 1290 | USD 1.800
  → Jerónimo Salguero 1800 | USD 800
  → Juana Manso 740 | USD 1.300
  → Ugarteche 3100 | USD 650
  → Uriburu 1700 | $ 640.000
  → Gascon 826 | USD 700
  → Serrano 629 | USD 800
  → Mexico 853 | USD 400
  → Juncal 1100 | USD 650
  → Av. Independencia 2300 | $ 110.000
  → Pasaje Santa Rosa 5100 | USD 1.300
  → Lola Mora 400 | USD 1.300
  → Peña 2500 | USD 750
  → Nicaragua 4800 | USD 1.500
  → Avenida Dorrego 1700 | USD 1.300
  → Republica Arabe Siria 3100 | USD 1.250
  → Ravignani 1300 | USD 650

--- PÁGINA 13 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-13.html
  → 30 propiedades encontradas
  → Santa Fe 3700 | USD 1.990
  → None None | $ 640.000
  → Ayacucho 1900 | USD 3.000
  → Callao 900 | $ 900.000
  → Aime Paine 1100 | USD 3.600
  → Rep Arabe Siria 3200 | USD 1.400
  → Migueletes 500 | USD 1.050
  → Arroyo 800 | USD 850
  → Av. Alvear 1500 | USD 2.500
  → Alicia M. De Justo 700 | USD 700
  → Godoy Cruz 2900 | USD 1.500
  → Guemes 3600 | USD 1.650
  → Estado De Palestina 500 | $ 780.000
  → Corrientes 3900 | USD 1.600
  → Pavon 1900 | USD 900
  → Ramón Falcón 1300 | USD 1.100
  → Austria 1900 | USD 1.800
  → Juana Manso 740 | USD 2.200
  → Av. Ing. Huergo 475 | USD 900
  → Av. Ing. Huergo 475 | USD 1.300
  → Echeverria 2400 | $ 1.400.000
  → Julian Alvarez 900 | $ 750.000
  → None None | $ 1.800.000
  → Arevalo 2200 | USD 1.800
  → Jorge Newbery 2460 | USD 1.500
  → Thames 2300 | USD 1.800
  → Fitz Roy 2200 | USD 1.200
  → Virrey Loreto 2426 | $ 55.000
  → Juana Manso 1122 | USD 2.500
  → None None | USD 1.600

--- PÁGINA 14 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-14.html
  → 30 propiedades encontradas
  → Avenida Luis María Campos 1400 | USD 800
  → Salguero, Jeronimo 1810 | USD 700
  → Olleros 2400 | USD 1.500
  → Av. Medrano 1900 | USD 700
  → None None | USD 3.400
  → Arce 591 | USD 600
  → Freire 2443 | USD 850
  → Salguero 1633 | USD 650
  → Costa Rica 4100 | USD 1.500
  → Peña 2033 | USD 630
  → None None | $ 820.000
  → Monroe 1500 | USD 1.100
  → Billinghurts 1300 | USD 650
  → Lola Mora 457 | $ 1.690.000
  → Arevalo 1720 | USD 650
  → Bonpland 1300 | USD 750
  → Guatemala 4500 | USD 800
  → Av. Luis Maria Campos 1000 | USD 950
  → Gabriela Mistral 2462 | USD 55
  → None None | USD 700
  → Av. Independencia 2300 | USD 1.200
  → Cordoba 4115 | USD 550
  → Benjamin Matienzo 1724 | USD 750
  → 11 De Septiembre 2500 | $ 990.000
  → Ciudad De La Paz 2969 | USD 440
  → Billinghurst 1323 | USD 813
  → Av. Corrientes 6300 | USD 700
  → Guido 1900 | USD 1.400
  → Avenida Libertador 5740 | USD 5.000
  → None None | USD 850

--- PÁGINA 15 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-15.html
  → 30 propiedades encontradas
  → Azcuenaga 1500 | USD 2.200
  → Av. Santa Fe 3300 | USD 850
  → 2 Ambientes Av. Dorrego 1700 | USD 1.800
  → Laprida 1800 | USD 600
  → Republica De La India 3000 | USD 650
  → Moreau De Justo 1848 | Consultar
  → None None | USD 800
  → Ugarteche 3193 | USD 550
  → None None | USD 500
  → Viamonte 675 | USD 750
  → Avenida Dorrego 1781 | $ 1.400.000
  → Villanueva 1300 | USD 2.050
  → Rodriguez Peña 1900 | USD 1.800
  → Beruti 4500 | USD 800
  → Carlos Gardel 3100 | $ 800.000
  → Carlos Calvo 1500 | $ 550.000
  → Berutti 4450 | USD 480
  → Fray Justo Santa María De Oro 2386 | $ 700.000
  → Av. Belgrano 1300 | $ 940.000
  → Alsina 1200 | $ 860.000
  → Leon Pagano 2700 | USD 550
  → Venezuela 818 | $ 600.000
  → Fitz Roy 1400 | USD 1.000
  → Zapata 359 | USD 800
  → None None | USD 500
  → Oro 2300 | USD 2.200
  → Sarmiento 3700 | USD 700
  → Pacheco De Melo 1900 | USD 300
  → Av. Del Libertador 5740 | USD 1.300
  → None None | USD 500

--- PÁGINA 16 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-16.html
  → 30 propiedades encontradas
  → Lola Mora 400 | USD 2.500
  → Temporario Duplex Con Amenities Ravignani 2100 | USD 950
  → Teodoro Garcia 2300 | USD 740
  → Marcelo T De Alvear 800 | USD 500
  → Juana Manso 400 | USD 2.850
  → Avenida Callao 1440 | USD 900
  → Del Libertador 8540 | USD 1.700
  → Montañeses 2600 | USD 700
  → Avenida Ingeniero Huergo 551 | USD 1.000
  → Coronel Niceto Vega 5700 | USD 650
  → Fray Justo Santa Maria De Oro 2752 | USD 600
  → Peña 2400 | USD 3.000
  → Ángel Justiniano Carranza 1300 | USD 1.400
  → Juana Manso 552 | USD 2.200
  → None None | $ 2.500
  → None None | USD 400
  → Azcuenaga 1000 | USD 1.100
  → Av. De Mayo 700 | $ 660.000
  → Lafinur 3100 | USD 1.500
  → Lafinur 2900 | USD 1.800
  → Guido 1900 | USD 1.600
  → Freire 2443 | USD 850
  → None None | USD 800
  → La Pampa 1100 | USD 1.300
  → Fitz Roy 1453 | USD 800
  → Ugarteche 2800 | USD 770
  → Aime Paine 1100 | USD 3.200
  → Dorrego 2187 | USD 1.235
  → Güemes 3100 | USD 1.400
  → Guevara 480 | $ 650.000

--- PÁGINA 17 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-17.html
  → 30 propiedades encontradas
  → Juana Manso 1141 | USD 2.200
  → Dorrego 2765 | USD 1.200
  → None None | USD 1.000
  → Avda Belgrano 1300 | $ 750.000
  → José León Pagano 2600 | USD 1.300
  → Mendoza 4500 | USD 700
  → Concepción Arenal 3500 | $ 650.000
  → Juana Manso 500 | USD 3.000
  → Aime Paine 1100 | USD 7.300
  → Bartolomé Mitre 1444 | $ 750.000
  → Av. Quintana 400 | USD 4.800
  → Pasaje Tunez 2500 | USD 2.200
  → Migueletes 600 | USD 3.400
  → Guemes 2900 | USD 1.900
  → Ortega Y Gasset 1700 | USD 650
  → Santa Fe 2600 | USD 700
  → None None | USD 480
  → Jerónimo Salguero 2750 | $ 4.900
  → Av. Cordoba 5200 | USD 1.600
  → Juana Manso 1600 | USD 1.550
  → Cabrera 5040 | $ 1.250.000
  → Thames 2400 | $ 650.000
  → Fray Justo Santa María De Oro 2700 | USD 1.600
  → None None | USD 700
  → Mariscal Antonio José De Sucre 950 | USD 550
  → Gorriti 4500 | USD 650
  → Copernico 2500 | USD 330
  → Boulevard Rosario Vera Peñaloza 599 | USD 1.900
  → Conde 1041 | USD 750
  → Avenida Santa Fe 5030 | USD 750

--- PÁGINA 18 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-18.html
  → 30 propiedades encontradas
  → None None | USD 950
  → Paraguay 5500 | USD 900
  → Pico 2300 | USD 2.700
  → Aime Paine 1100 | USD 5.000
  → Santa Fe 3300 | USD 850
  → Hipolito Yrigoyen 723 | USD 500
  → Avenida Ingeniero Huergo 475 | USD 900
  → Gorriti 3900 | USD 900
  → Ciudad De La Paz 1900 | USD 400
  → Av. Libertador 7500 | USD 800
  → Azopardo 700 | USD 1.600
  → Tagle 2500 | USD 850
  → Pacheco De Melo 1800 | USD 550
  → Avenida Juramento 2806 | $ 1.200.000
  → Bv Chenaut 1911 | USD 700
  → Rodríguez Peña 1533 | USD 800
  → None None | USD 1.000
  → Baez 700 | USD 700
  → Santos Dumont 2300 | USD 700
  → O Higgins 2700 | USD 1.100
  → Beruti 2400 | $ 1.400.000
  → Virrey Del Pino 2365 | USD 800
  → None None | USD 1.500
  → Carlos Pellegrini 800 | USD 450
  → None None | USD 1.300
  → Tucuman 540 | USD 500
  → Avenida Santa Fe 5030 | $ 900
  → Salta 500 | USD 600
  → Franklin Roosevelt 2860 | USD 1.200
  → Nicaragua 6000 | USD 2.100

--- PÁGINA 19 ---
URL: https://www.zonaprop.com.ar/departamentos-alquiler-temporal-capital-federal-pagina-19.html
  → 30 propiedades encontradas
  → Lola Mora 420 | USD 2.500
  → Marcelo T.De Alvear 1700 | USD 2.000
  → Comodoro Pedro Zanni 300 | USD 900
  → Paraguay 5400 | USD 650
  → Esmeralda 853 | $ 750.000

In [11]:
if df_alquiler_temporal is not None:
    print(f"Total propiedades: {len(df_alquiler_temporal)}")
    display(df_alquiler_temporal.head(10))

    cols = ["Losa_Central","Aire_Acond","Apto_Credito",
            "Cochera","Seguridad","Luminoso","Balcon_Aterrazado"]
    print("\n📊 % con cada característica:")
    print((df_alquiler_temporal[cols].mean() * 100).round(1).astype(str) + "%")

Total propiedades: 3476

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,58810877,zonaprop,alquiler_temporal,USD 3.800,None,Lola Mora,400,None,Puerto Madero,...,Alquiler temporario de 3 ambientes amueblado e...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,0,0,1,1,0,0
1,2026-04-12,58731045,zonaprop,alquiler_temporal,USD 1.100,None,Piedras,1100,None,San Telmo,...,Corredor Inmobiliario responsable: Arq. Jorge ...,https://www.zonaprop.com.ar/propiedades/clasif...,5,0,0,0,0,1,1,0
2,2026-04-12,58586992,zonaprop,alquiler_temporal,USD 600,None,Av. Las Heras,2000,None,Recoleta,...,Alquiler temporario de Departamento 1 Ambiente...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,0,0
3,2026-04-12,58822120,zonaprop,alquiler_temporal,USD 2.200,None,Rosario Vera Peñaloza,500,None,Puerto Madero,...,Corredor Inmobiliario responsable: Arq. Jorge ...,https://www.zonaprop.com.ar/propiedades/clasif...,4,0,0,0,1,1,1,0
4,2026-04-12,57872253,zonaprop,alquiler_temporal,USD 1.150,None,Arenales,2300,None,Recoleta,...,Departamento de dos ambientes para alquiler te...,https://www.zonaprop.com.ar/propiedades/clasif...,5,0,1,0,1,1,1,0
5,2026-04-12,57863013,zonaprop,alquiler_temporal,USD 650,None,Av Rivadavia,5800,None,Caballito,...,Departamento de un ambiente en caballito para ...,https://www.zonaprop.com.ar/propiedades/clasif...,5,0,1,0,0,0,1,0
6,2026-04-12,58637629,zonaprop,alquiler_temporal,USD 1.450,None,Av Coronel Diaz,1400,None,Palermo,...,Departamento de tres ambientes en palermo para...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,1,0,0,0,0,0
7,2026-04-12,58584223,zonaprop,alquiler_temporal,USD 650,$ 115.000,Nuñez,2900,None,Núñez,...,Corredor Responsable: Ariel Champanier cucicba...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,1,0,0,0,1,0
8,2026-04-12,57130848,zonaprop,alquiler_temporal,USD 4.000,$ 600.000,Concepcion Arenal,2900,None,Palermo Hollywood,...,Alquiler Temporario Premium – Torre Concepción...,https://www.zonaprop.com.ar/propiedades/clasif...,4,0,0,0,1,1,1,0
9,2026-04-12,56314889,zonaprop,alquiler_temporal,USD 700,None,Marcelo T. De Alvear,500,9,Retiro,...,Departamento de 2 ambientes en alquiler tempor...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,0,0

📊 % con cada característica:
Losa_Central          7.0%
Aire_Acond           51.0%
Apto_Credito          0.2%
Cochera              16.0%
Seguridad            20.0%
Luminoso             66.4%
Balcon_Aterrazado     5.5%
dtype: object

# Venta

In [12]:
df_venta = run_scrapper_zonaprop('https://www.zonaprop.com.ar/departamentos-venta-capital-federal', 'venta', max_pages=600)

--- PÁGINA 1 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal.html
  → 25 propiedades encontradas
  → None None | USD 160.000
  → Posadas 1600 | USD 4.500.000
  → Jerónimo Salguero 700 | USD 135.000
  → Uriarte 2400 | USD 93.000
  → Malabia 2200 | USD 127.000
  → Avenida Corrientes 1900 | USD 118.130
  → Rio De Janeiro 1000 | USD 69.999
  → Tronador 2600 | USD 230.000
  → Vuelta De Obligado 3000 | USD 112.000
  → Olazabal 4100 | USD 352.000
  → Zuviria 449 | USD 226.000
  → Formosa 300 | USD 47.000
  → Rincón 1100 | USD 69.000
  → None None | USD 80.000
  → Arroyo 800 | USD 550.000
  → Monroe 4400 | USD 240.000
  → Pasteur 700 | USD 65.000
  → San Blas 2984 | USD 99.000
  → Avenida Cordoba 4200 | USD 153.000
  → Scalabrini Ortíz 2400 | USD 139.000
  → None None | USD 185.000
  → Nazca 2700 | USD 89.000
  → Av. Estado De Israel 4700 | USD 115.000
  → Contralmirante Martin Guerrico 5400 | USD 59.900
  → Av La Plata 689 | USD 846.700

--- PÁGINA 2 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-2.html
  → 25 propiedades encontradas
  → Juan B. Justo 9000 | USD 107.000
  → Libertador 7400 | USD 850.000
  → Republica Árabe Siria 2955 | USD 570.000
  → Juncal 900 | USD 2.100.000
  → Araoz 2700 | USD 375.000
  → Talcahuano 400 | USD 54.000
  → Chile 1200 | USD 70.000
  → Estado De Palestina 800 | USD 125.000
  → Perón 2759 | USD 95.000
  → Rodríguez Peña 1676 | USD 138.000
  → Gelly Y Obes 2200 | USD 835.000
  → Costa Rica 6000 | USD 127.000
  → Av Rivadavia 4390 | USD 69.000
  → La Pampa 2400 | USD 150.000
  → Avenida Francisco Beiró 4400 | USD 86.000
  → Av.Caseros 700 | USD 109.900
  → Sanchez De Bustamante 2300 | USD 180.000
  → Av. Del Libertador 5000 | USD 565.000
  → Cabello 3300 | USD 395.000
  → Av Nazca 900 | USD 99.900
  → Avenida Del Libertador 7500 | USD 595.000
  → Av. Nazca 900 | USD 135.000
  → Maturin 2868 | USD 179.999
  → Mercedes 600 | USD 88.000
  → Guido 1999 | USD 262.000

--- PÁGINA 3 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-3.html
  → 25 propiedades encontradas
  → Malvinas Argentinas 148 | USD 477.800
  → Moldes 1400 | USD 253.000
  → Av. Medrano 1000 | USD 145.000
  → Peña 2700 | USD 98.000
  → Migueletes 500 | USD 610.000
  → Las Heras 4000 | USD 389.000
  → Lavalle 3000 | USD 59.000
  → Araoz 200 | USD 445.000
  → Av. Santa Fe 3601 | USD 473.000
  → Salguero 2500 | USD 1.105.000
  → Concepción Arenal 2989 | USD 245.000
  → Bernardo Irigoyen 1300 | USD 75.000
  → Lambare 1100 | USD 79.000
  → Paso 700 | USD 270.000
  → Paraguay 600 | USD 68.000
  → Salguero 2585 | USD 1.080.000
  → Jose Maria Moreno 800 | USD 87.000
  → Junin 1400 | USD 130.000
  → Av. Las Heras 3900 | USD 615.000
  → Concepción Arenal 3900 | USD 325.000
  → Colombres 500 | USD 66.500
  → Av. Cramer 2451 | USD 270.875
  → Alvarez Thomas 800 | USD 90.687
  → Gallo 700 | USD 141.700
  → Rodriguez Pena 1200 | USD 390.000

--- PÁGINA 4 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-4.html
  → 25 propiedades encontradas
  → Bulnes 1600 | USD 71.000
  → Av. Córdoba 4300 | USD 110.000
  → Paraguay 3000 | USD 179.000
  → Humboldt 1300 | USD 357.436
  → Pilar 1300 | USD 164.000
  → Migueletes 1000 | USD 199.670
  → None None | USD 168.000
  → Montes De Oca 1100 | USD 275.000
  → Posadas 1264 | USD 670.000
  → Ciudad De La Paz 3500 | USD 182.573
  → Francisco Bilbao 2200 | USD 170.000
  → Tres Arroyos 3072 | USD 83.500
  → Av Olazabal 4800 | USD 154.080
  → Maipu 400 | USD 90.000
  → Billinghurts 400 | USD 89.900
  → Ortiz De Ocampo 2600 | USD 235.000
  → Paroissien 2600 | USD 190.000
  → Av La Plata 689 | USD 1.445.900
  → La Pampa 2868 | USD 91.500
  → French 3500 | USD 399.000
  → Iberá 1500 | USD 139.000
  → La Pampa 2900 | USD 151.800
  → Colombres 700 | USD 118.000
  → San Martin De Tours 2800 | USD 890.000
  → Arenales 1100 | USD 335.000

--- PÁGINA 5 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-5.html
  → 25 propiedades encontradas
  → Av. Pueyrredon, Honorio, Dr 1850 | USD 89.500
  → Migueletes 2200 | USD 220.000
  → Presidente José Evaristo Uriburu 1500 | USD 650.000
  → Catamarca 600 | USD 60.000
  → Olleros 1700 | USD 580.000
  → Bahía Blanca 400 | USD 135.000
  → Virrey Cevallos 300 | USD 99.000
  → Avalos 2100 | USD 190.000
  → Marcelo Torcuato De Alvear 1300 | USD 60.000
  → Av. Santa Fe 3300 | USD 410.000
  → Uriarte 2200 | USD 99.000
  → Ohiggins 2700 | USD 472.000
  → Arcos 2000 | USD 180.000
  → Acoyte 1500 | USD 215.000
  → Avenida Libertador 3800 | USD 3.500.000
  → Avellaneda 2300 | USD 398.000
  → Pichincha 1100 | USD 49.900
  → Arenales 2949 | USD 195.000
  → Araoz 2500 | USD 489.500
  → Lavalle 3700 | USD 115.000
  → Av Córdoba 4300 | USD 110.000
  → Libertad 300 | USD 57.000
  → Alberti 1600 | USD 69.000
  → Julieta Lanteri 1775 | USD 1.100.000
  → Alsina Adolfo 1500 | USD 72.000

--- PÁGINA 6 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-6.html
  → 25 propiedades encontradas
  → O. De Ocampo 3195 | Consultar
  → Mansilla 3000 | USD 119.629
  → None None | USD 115.000
  → Av. Cabildo 4667 | USD 185.000
  → Marcelo T De Alvear 2100 | USD 82.000
  → Av Pedro Goyena 655 | USD 871.709
  → Avenida San Martín 2900 | USD 186.900
  → Emilio Lamarca 800 | USD 103.999
  → None None | USD 51.000
  → Ortega Y Gasset 1650 | USD 385.000
  → Manuel Ugarte 3800 | USD 249.000
  → Humboldt 2200 | USD 112.000
  → Av. Cabildo 2700 | USD 115.000
  → Av. Riestra 5500 | USD 63.000
  → Santos Dumont 3400 | USD 172.000
  → Jorge Newbery 2400 | USD 230.000
  → Arenales 3509 | USD 215.000
  → Vidt 2000 | USD 365.000
  → Terrazas De Volcán Zelarrayán 1600 | USD 80.000
  → Boyaca 700 | USD 100.000
  → Av. Cabildo 3700 | USD 125.000
  → Av. Olazabal 4500 | USD 122.000
  → Mariscal Antonio José De Sucre 4200 | USD 95.000
  → Neuquén 1881 | USD 70.000
  → None None | USD 70.000

--- PÁGINA 7 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-7.html
  → 25 propiedades encontradas
  → Av. Alvarez Thomas 2000 | USD 301.600
  → Torre Bartolome Mitre 1400 | USD 94.000
  → Azucena Villaflor 500 | USD 2.147.000
  → Tamborini 2600 | USD 180.000
  → Campichuelo 260 | USD 149.000
  → Av. Cerviño 3900 | USD 985.700
  → Juncal 2300 | USD 110.000
  → Avenida Francisco Beiró 5100 | USD 175.000
  → Republica De La India 2900 | USD 430.000
  → Juana Manso 1400 | USD 650.000
  → Viamonte 2400 | USD 149.500
  → None None | USD 91.136
  → Jorge Newbery 3400 | USD 200.000
  → Sucre 2000 | USD 439.000
  → Calle Monseñor Vicente Zazpe 3100 | USD 290.000
  → Uspallata 700 | USD 89.000
  → Pacheco De Melo Jose A 2000 | USD 550.000
  → Coronel Diaz 2100 | USD 910.000
  → Av. Santa Fe 4000 | USD 625.000
  → Av. Corrientes 3841 | USD 122.000
  → Amenabar 2100 | USD 179.000
  → Migueletes 2300 | USD 299.000
  → French 2900 | USD 89.000
  → Mansilla 3000 | USD 297.286
  → Tamborini 2600 | USD 398.000

--- PÁGINA 8 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-8.html
  → 25 propiedades encontradas
  → Mendoza 5000 | USD 189.900
  → Virrey Aviles 2700 | USD 235.562
  → Avenida Riestra 5600 | USD 139.000
  → Murillo 1000 | USD 90.000
  → Crámer 2400 | USD 560.000
  → San Nicolas 5200 | USD 172.000
  → Bernardo De Irigoyen 1100 | USD 75.000
  → Adolfo Alsina 3100 | USD 105.000
  → Besares 4700 | USD 215.000
  → Alberdi, Juan B., Av 5500 | USD 96.750
  → Dragones 1800 | USD 470.000
  → Av. Cramer 3206 | USD 275.000
  → Rodríguez Peña 1500 | USD 1.250.000
  → Avenida Olazabal 4800 | USD 210.000
  → Costa Rica 4900 | USD 780.000
  → Juan Bautista Alberdi 2600 | USD 174.000
  → Godoy Cruz 2800 | USD 194.770
  → Cramer 1600 | USD 230.000
  → Planes 700 | USD 119.000
  → Membrillar 300 | USD 75.000
  → Emilio Castro 6100 | USD 187.137
  → Piedras 837 | USD 115.000
  → Av Cramer 2700 | USD 138.400
  → Rawson 300 | USD 150.000
  → Brandsen 900 | USD 160.000

--- PÁGINA 9 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-9.html
  → 25 propiedades encontradas
  → Tronador 2600 | USD 89.000
  → Juncal 3700 | USD 400.000
  → J. F. Kennedy 2800 | USD 790.000
  → Arenales 800 | USD 380.000
  → Talcahuano 900 | USD 240.000
  → Trinidad Guevara 300 | USD 2.600.000
  → Avenida Del Libertador 1024 | USD 310.000
  → Pres.Jose Uriburu 300 | USD 115.000
  → Montañeses 2600 | USD 119.000
  → Carlos Calvo 1500 | USD 70.000
  → República De Eslovenia 1988 | Consultar
  → Rivadavia 1700 | USD 125.000
  → Suarez 1500 | USD 116.000
  → Gurruchaga 2100 | USD 118.000
  → Neuquén 2100 | USD 435.000
  → Av Nazca 4600 | USD 115.000
  → Crisologo Larralde 2600 | USD 135.000
  → None None | USD 680.000
  → None None | USD 140.000
  → None None | USD 153.000
  → Oliden 4400 | USD 95.000
  → Gorriti 4458 | USD 151.000
  → Armenia 1200 | USD 378.725
  → Avenida La Plata 500 | USD 109.900
  → Ibera 3800 | USD 95.000

--- PÁGINA 10 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-10.html
  → 25 propiedades encontradas
  → Av. Libertador 7600 | USD 460.000
  → Gral. Cesar Diaz 2868 | USD 185.000
  → Humboldt 1900 | USD 520.000
  → Granaderos 200 | USD 93.891
  → Caracas 500 | USD 130.000
  → None None | USD 139.000
  → Monasterio 100 | USD 224.000
  → Oliden 4400 | USD 110.000
  → None None | USD 380.000
  → Araoz 500 | USD 79.000
  → Humboldt 1300 | USD 241.909
  → Arenales 2521 | USD 216.454
  → La Pampa 2900 | USD 394.000
  → None None | USD 125.000
  → Lavalle 3200 | USD 185.000
  → Bolivia 3000 | USD 320.000
  → Congreso 2300 | USD 210.000
  → Av. Donato Alvarez 1220 | USD 69.500
  → Ramon Falcon 1900 | USD 169.900
  → Bartolome Mitre 1444 | USD 100.000
  → Thames 500 | USD 130.000
  → Charcas 2800 | USD 160.000
  → Beruti 3800 | USD 370.000
  → O’Higgins 1900 | USD 550.000
  → Avda. Independencia 1300 | USD 79.800

--- PÁGINA 11 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-11.html
  → 25 propiedades encontradas
  → Av. Santa Fe 3600 | USD 1.000.000
  → Av Callao 1100 | USD 290.000
  → Av Del Libertador 800 | USD 330.000
  → Paraná 800 | USD 109.000
  → Cuenca 2500 | USD 139.000
  → Av. Directorio 1621 | USD 790.000
  → Tomas Liberti 1100 | USD 122.570
  → Combate De Los Pozos 1300 | USD 75.000
  → Marcelo T De Alvear 1300 | USD 202.000
  → Las Heras 1800 | USD 179.256
  → Salguero 1100 | USD 118.000
  → Humberto Primo 1200 | USD 150.000
  → Dr Enrique Finochietto 900 | USD 255.800
  → Paunero 2800 | USD 120.000
  → Paraguay 2000 | USD 165.000
  → Bulnes 1800 | USD 220.000
  → Cabildo 3500 | USD 136.080
  → Av. Santa Fe 3600 | USD 160.000
  → Directorio 1641 | USD 360.200
  → Av. Scalabrini Ortiz 901 | USD 336.600
  → Paraguay 2400 | USD 215.000
  → Fragata Presidente Sarmiento 1600 | USD 83.162
  → Raul Scalabrini Ortiz 100 | USD 139.000
  → José Bonifacio 300 | USD 126.000
  → Arévalo 1474 | USD 115.000

--- PÁGINA 12 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-12.html
  → 25 propiedades encontradas
  → San Nicolas 2400 | USD 108.000
  → Amenabar 2800 | USD 159.000
  → None None | USD 115.000
  → Avenida Directorio 100 | USD 275.000
  → Thorne 300 | USD 129.000
  → Correa 2300 | USD 139.600
  → Manuel Ugarte 2000 | USD 125.000
  → Av. Libertador 7200 | USD 195.000
  → Tucumán 3400 | USD 393.249
  → Echeverria 1200 | USD 490.000
  → Terrero 600 | USD 199.000
  → None None | USD 235.000
  → Holmberg 4000 | USD 119.000
  → Gurruchaga 2150 | USD 202.100
  → Echeverria 5000 | USD 319.000
  → Torre Bartolome Mitre 1400 | USD 74.500
  → Migueletes 1600 | USD 416.460
  → Av. Triunvirato 3000 | USD 144.000
  → Zapiola 1400 | USD 566.713
  → Valentin Gomez 3000 | USD 119.000
  → Bonpland 1800 | USD 205.000
  → Altolaguirre 3000 | USD 125.000
  → Olazabal 2700 | USD 475.000
  → Migueletes 1700 | USD 135.000
  → Rio De Janeiro 500 | USD 136.800

--- PÁGINA 13 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-13.html
  → 25 propiedades encontradas
  → Libertad 1600 | USD 280.000
  → El Salvador 4800 | USD 129.000
  → Marta Lynch 400 | USD 1.390.000
  → Avenida Rivadavia 3100 | USD 126.500
  → Monroe 1300 | USD 695.000
  → None None | USD 116.900
  → *Libertador 5400 | USD 1.200.000
  → Jorge Newbery 1500 | USD 570.000
  → Humboldt 2400 | USD 116.000
  → Lavalleja 100 | USD 72.000
  → República De La India 2700 | USD 350.000
  → Juana Manso 1400 | USD 1.707.048
  → None None | USD 640.000
  → Humboldt 1300 | USD 196.769
  → Avenida Santa Fe 5200 | USD 198.111
  → Paroissien 2500 | USD 235.000
  → Echeverría 800 | USD 2.517.000
  → Venezuela 1200 | USD 168.000
  → Av Dr Ricardo Balbin 2600 | USD 122.850
  → Aranguren 2000 | USD 130.500
  → Av. Del Libertador 7400 | USD 1.900.000
  → Reconquista 600 | USD 170.000
  → None None | USD 129.600
  → Juana Manso 1100 | USD 540.000
  → Sucre 2400 | USD 129.500

--- PÁGINA 14 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-14.html
  → 25 propiedades encontradas
  → Bilbao Francisco 1500 | USD 240.000
  → Freire 2100 | USD 939.031
  → Ciudad De La Paz 3700 | USD 200.200
  → Moldes 3100 | USD 88.000
  → Vicente Lopez 1900 | USD 89.900
  → Av Gral Paz 10 700 | USD 62.000
  → Av Juan B Justo 2350 | USD 78.000
  → Arenales 3000 | USD 155.000
  → Lemos 300 | USD 154.900
  → Galvan 2800 | USD 127.000
  → Suipacha 1300 | USD 580.000
  → Dr Enrique Finochietto 990 | USD 251.100
  → Juana Manso 1500 | USD 465.000
  → Peña 2600 | USD 273.000
  → O'Higgins 1400 | USD 620.000
  → None None | USD 195.500
  → Carlos Calvo 4063 | USD 163.000
  → Azucena Villaflor 500 | USD 1.750.000
  → Av Las Heras 3500 | USD 135.000
  → Moldes 3141 | USD 290.000
  → Bahia Blanca 2400 | USD 118.000
  → Paso 700 | USD 114.500
  → Pacheco De Melo 2400 | USD 395.000
  → Paraguay 800 | USD 330.000
  → Valle 505 | USD 95.000

--- PÁGINA 15 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-15.html
  → 25 propiedades encontradas
  → Avenida Boedo 255 | USD 117.500
  → Callao 900 | USD 310.000
  → Hidalgo 1000 | USD 110.000
  → Av Coronel Diaz 2500 | USD 350.000
  → Avalos 2100 | USD 133.400
  → Alsina 2100 | USD 70.000
  → Guatemala 5700 | USD 335.000
  → Godoy Cruz 2300 | USD 272.000
  → Coronel Diaz 2546 | USD 499.000
  → Mariscal Antonio José De Sucre 2400 | USD 267.500
  → Amenabar 2400 | USD 195.000
  → Cuba 4500 | USD 616.234
  → Las Heras 1700 | USD 1.175.000
  → Piedras 1000 | USD 74.000
  → Félix Foullier 5800 | USD 115.000
  → Esmeralda 1200 | USD 382.000
  → Pavon 1200 | USD 25.000
  → Juncal 2600 | USD 95.000
  → Jose Hernandez 1700 | USD 1.900.000
  → Paraguay 4200 | USD 150.000
  → Yatay 641 | USD 80.500
  → Rivadavia 1700 | USD 125.000
  → Bilbao 2048 | USD 580.000
  → Marcelo T. De Alvear 2100 | USD 149.000
  → Arcos 2400 | USD 265.788

--- PÁGINA 16 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-16.html
  → 25 propiedades encontradas
  → Hidalgo 800 | USD 77.000
  → Colpayo 300 | USD 185.000
  → Pieres 200 | USD 75.000
  → Sucre 1500 | USD 308.709
  → Juana Manso 1800 | USD 760.000
  → Cnel. Ramón L. Falcón 6700 | USD 225.000
  → Cuenca 4500 | USD 120.000
  → Virrey Del Pino 1700 | USD 700.000
  → None None | USD 109.000
  → Quito 4300 | USD 140.000
  → Lugones 2700 | USD 240.000
  → Rojas 300 | USD 111.573
  → Felipe Vallese 400 | USD 195.000
  → Av. Cordoba 3700 | USD 187.000
  → Av. Santa Fe 5022 | USD 286.900
  → Avda. Pueyyredon 1705 | USD 115.000
  → Alejandro Magariños Cervantes 2700 | USD 72.300
  → Ayacucho 600 | USD 85.000
  → Ugarte 3000 | USD 85.800
  → Av. Pedro Goyena 1745 | USD 931.300
  → Tucuman 3600 | USD 77.526
  → Jorge Newbery 2400 | USD 245.615
  → Cabello 3400 | USD 280.000
  → Doctor Marcelo J. Fitte 1700 | USD 197.000
  → Beruti 4500 | USD 416.500

--- PÁGINA 17 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-17.html
  → 25 propiedades encontradas
  → Moldes 1600 | USD 210.481
  → Rosario Vera Peñaloza 599 | USD 645.000
  → Congreso 5000 | USD 141.207
  → Rivadavia, Av 5268 | USD 68.000
  → Estado De Palestina 1100 | USD 280.000
  → Nueva York 3800 | USD 310.000
  → Av. Monroe 4445 | USD 119.000
  → Av. Figueroa Alcorta 3500 | USD 2.000.000
  → Chile 2378 | USD 85.000
  → Esmeralda 800 | USD 60.000
  → Julieta Lanteri 1241 | USD 1.700.000
  → Estomba 3200 | USD 130.000
  → Pinto 4700 | USD 119.000
  → Cordoba 3100 | USD 89.000
  → Libertad 800 | USD 100.000
  → Av. Santa Fe 1100 | USD 415.000
  → Acoyte 100 | USD 99.000
  → Blanco Encalada 2600 | USD 178.500
  → Av. Juan Bautista Alberdi 2400 | USD 214.000
  → Viamonte 1700 | USD 140.000
  → Av. Rivadavia 7113 | USD 148.000
  → Montevideo 1700 | USD 465.000
  → Lemos 200 | USD 134.900
  → Superi 1500 | USD 1.500.000
  → Av. Las Heras 1800 | USD 259.978

--- PÁGINA 18 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-18.html
  → 25 propiedades encontradas
  → Paraguay 3500 | USD 475.000
  → Freire 2400 | USD 115.000
  → Cabrera 3400 | USD 210.500
  → Corrientes, Avda 6000 | USD 125.000
  → Conde 1400 | USD 549.999
  → Agrelo 4200 | USD 142.500
  → Arribeños 2800 | Consultar
  → Diaz Colodrero 2700 | USD 235.000
  → Avenida Juan B. Justo 3300 | USD 121.000
  → Cucha Cucha 1100 | USD 235.000
  → Newbery Jorge 1800 | USD 260.000
  → None None | USD 166.000
  → Avenida Santa Fe 1200 | USD 200.000
  → Cramer 1700 | USD 245.000
  → Concepción Arenal 2400 | USD 295.000
  → 3 De Febrero 2900 | USD 356.580
  → Av. Federico Lacroze 3400 | USD 1.600.000
  → Las Heras Gral. Av 2900 | USD 325.000
  → Juana Manso 1500 | USD 375.000
  → Rodriguez Peña 1100 | USD 240.000
  → Paraguay 2000 | USD 152.700
  → Del Libertador Av 5500 | USD 159.500
  → Tucuman 2892 | USD 69.500
  → Soler 5755 | USD 646.000
  → Costa Rica 5400 | USD 165.000

--- PÁGINA 19 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-19.html
  → 25 propiedades encontradas
  → None None | USD 95.000
  → San Ignacio 3600 | USD 135.000
  → Anchorena 1700 | USD 149.500
  → Soldado De La Independencia 1300 | USD 139.000
  → Del Barco Centenera 700 | USD 93.000
  → Vidal 1700 | USD 89.000
  → Av. Gral Las Heras 2963 | USD 143.000
  → Av. Rivadavia 2100 | USD 98.000
  → Gelly 3400 | USD 1.250.000
  → Tamborini 2600 | USD 122.000
  → Dr. Emilio Ravignani 2100 | USD 205.000
  → Av. San Isidro 4700 | USD 101.000
  → Camila O´Gorman 400 | USD 615.000
  → Soldado De La Independencia 800 | USD 192.195
  → Av. Callao 2000 | USD 485.000
  → Av. Cabildo 3000 | USD 113.230
  → Demaría 4500 | USD 3.600.000
  → Quintana 4600 | USD 125.000
  → Pacheco De Melo 1800 | USD 215.000
  → Pedro Morán 3300 | USD 137.000
  → Quesada 2664 | USD 159.000
  → Estados Unidos 1800 | USD 138.000
  → Azopardo 1300 | USD 189.000
  → Jujuy, Av 645 | USD 97.500
  → Virrey Aviles 2700 | USD 276.700

--- PÁGINA 20 ---
URL: https://www.zonaprop.com.ar/departamentos-venta-capital-federal-pagina-20.html
  → 25 propiedades encontradas
  → Pieres 800 | USD 110.000
  → Vuelta De Obligado 4800 | USD 106.505
  → Julieta Lanteri 1700 | USD 800.000
  → Billinghurst 1100 | USD 199.000
  → Avenida Libertador 7400 | USD 765.000
  → Jorge Newbery 1800 | USD 220.000
  → Cuba 1800 | USD 328.900
  → Quintana 500 | USD 850.000
  → Cespedes 3600 | USD 109.000
  → Costa Rica 5500 | USD 212.000
  → Billinghurst 1700 | USD 225.000
  → Arcos 1200 | USD 780.000
  → Venezuela 900 | USD 88.500
  → Cramer 2500 | USD 259.000
  → Santa Fe 3600 | USD 150.000
  → None None | USD 179.000
  → Constitución 3100 | USD 225.010
  → Av Congreso 2361 | USD 94.900
  → Lavalleja 865 | USD 129.870
  → Olazabal 5400 | USD 200.913
  → None None | USD 448.000
  → Juncal 2000 | USD 375.000
  → Av. Fco. Beiro 4515 | USD 301.200
  → Ecuador 1000 | USD 188.000
  → Avenida Belgrano 3600 | USD 140.000

--- PÁGINA 21 ---

In [14]:
if df_venta is not None:
    print(f"Total propiedades: {len(df_venta)}")
    display(df_venta.head(10))

    cols = ["Losa_Central","Aire_Acond","Apto_Credito",
            "Cochera","Seguridad","Luminoso","Balcon_Aterrazado"]
    print("\n📊 % con cada característica:")
    print((df_venta[cols].mean() * 100).round(1).astype(str) + "%")

Total propiedades: 16274

,Fecha_Scraping,Posting_ID,Sito,Operación,Precio,Expensas,Calle,Altura,Piso,Barrio,...,Descripción,Link,Amenities,Losa_Central,Aire_Acond,Apto_Credito,Cochera,Seguridad,Luminoso,Balcon_Aterrazado
0,2026-04-12,58398326,zonaprop,venta,USD 160.000,$ 126.347,None,None,None,Villa Crespo,...,Hermoso tres ambientes reciclado en sexto piso...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
1,2026-04-12,57150909,zonaprop,venta,USD 4.500.000,$ 4.600.000,Posadas,1600,None,Recoleta,...,"Posadas esquina Bioy Casares, emblemático edif...",https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,1,1,0,0
2,2026-04-12,58790026,zonaprop,venta,USD 135.000,$ 230.000,Jerónimo Salguero,700,None,Almagro,...,"Departamento 2 ambientes con balcón al frente,...",https://www.zonaprop.com.ar/propiedades/clasif...,1,1,0,0,0,0,1,0
3,2026-04-12,58499682,zonaprop,venta,USD 93.000,$ 220.000,Uriarte,2400,None,Palermo Soho,...,Dos ambientes reciclado y amueblado (opcional)...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
4,2026-04-12,58164322,zonaprop,venta,USD 127.000,$ 230.000,Malabia,2200,None,Palermo,...,3 ambientes. Lateral. 58 M2. Vista parcial. To...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,0,0,1,0
5,2026-04-12,57689076,zonaprop,venta,USD 118.130,None,Avenida Corrientes,1900,None,Balvanera,...,Met avenue se erige en pleno centro de Buenos ...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,0,0,1,0,0,0
6,2026-04-12,58701979,zonaprop,venta,USD 69.999,$ 66.400,Rio De Janeiro,1000,None,Caballito,...,Excelente 2 ambientes en el corazón de caballi...,https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,1,0,0,1,0
7,2026-04-12,57079611,zonaprop,venta,USD 230.000,$ 325.000,Tronador,2600,None,Belgrano,...,"¡ 5 amb, balcón al frente Y cochera! ¡ en cogh...",https://www.zonaprop.com.ar/propiedades/clasif...,0,0,0,0,1,0,1,0
8,2026-04-12,55317601,zonaprop,venta,USD 112.000,None,Vuelta De Obligado,3000,None,Núñez,...,Monoambiente/ Studio de 29 m2 con salida a bal...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,1,0,0,0,1,0
9,2026-04-12,53143147,zonaprop,venta,USD 352.000,$ 170.000,Olazabal,4100,None,Villa Urquiza,...,Te presentamos este luminoso departamento de 3...,https://www.zonaprop.com.ar/propiedades/clasif...,3,0,1,0,1,0,1,0

📊 % con cada característica:
Losa_Central         14.1%
Aire_Acond           31.4%
Apto_Credito         11.8%
Cochera              42.7%
Seguridad            24.7%
Luminoso             74.4%
Balcon_Aterrazado    13.0%
dtype: object